# This is an optional configuration file for fingerprint authentication. If you want to use fingerprint authentication, copy the contents of this file into your main hyprlock.conf file
# Credits to this the author of this PR: https://github.com/HyDE-Project/HyDE/pull/1682

auth {
    
    fingerprint {
        enabled = $HYPRLOCK_FINGERPRINT_ENABLED
        ready_message = "Scan fingerprint to unlock"
        present_message = "Scanning"
        retry_delay = 1200
    }
}

#hyprlang if HYPRLOCK_FINGERPRINT_ENABLED
$FPRINTD_ERR_LONG=To remove this message please remove any\n[hyprlock].fingerprint_enabled variable\nin your config.toml
$FPRINTD_ERROR=$(bash -c 'err=$(fprintd-verify 2>&1) || echo -e "Fingerprint Error:\n\"$err\"\n$FPRINTD_ERR_LONG" ' )

label {
    monitor =
    text = cmd[update:1000] echo "$FPRINTD_ERROR"
    color = $fail_color
    font_size = 20
    font_family = $fontFamily Bold
    position = 0, 10%
    halign = center
    valign = center
}
#hyprlang endif
