$scrPath=$HOME/.local/lib/hyde # set scripts path
$&=override # shorthand for override flag

# Main modifier
$mainMod = SUPER # windows key
$MOD = SUPER
$QUICKAPPS =
$BROWSER = hyde-shell open --fall firefox web-browser
$EDITOR = hyde-shell open --fall code-oss text-editor
$EXPLORER= hyde-shell open --fall dolphin file-manager
$TERMINAL = hyde-shell app -T
$LOCKSCREEN = hyprlock

# // █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
# // █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

# See https://wiki.hypr.land/Configuring/Keywords/


$list.environment=WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XDG_SESSION_DESKTOP XDG_CONFIG_HOME QT_QPA_PLATFORMTHEME
$unt="hyde-$XDG_SESSION_DESKTOP" # Holder for the unit name
$svc="service" # Holder for the service command
$scp="scope" # Holder for the scope command

$start.DBUS_SHARE_PICKER=dbus-update-activation-environment --systemd $list.environment # for XDPH
$start.SYSTEMD_SHARE_PICKER=systemctl --user import-environment $list.environment # for XDPH ( redundant with the first one )

$start.XDG_PORTAL_RESET=hyde-shell resetxdgportal.sh
$start.AUTH_DIALOGUE=hyde-shell app -t $svc -- polkitkdeauth.sh

$start.IDLE_DAEMON=hyde-shell app -u $unt-idle.service -t $svc -- hypridle
$start.BLUE_LIGHT_FILTER_DAEMON=hyde-shell app -u $unt-blue-light-filter.service -t $svc -- hyprsunset
$start.TEXT_CLIPBOARD=hyde-shell app -u $unt-text-clipboard.service -t $svc wl-paste --type text --watch cliphist store
$start.IMAGE_CLIPBOARD=hyde-shell app -u $unt-image-clipboard.service -t $svc wl-paste --type image --watch cliphist store
$start.CLIPBOARD_PERSIST=hyde-shell app -u $unt-clipboard-persist.service -t $svc wl-clip-persist --clipboard regular

$start.WALLPAPER=hyde-shell app -u $unt-wallpaper.service -t $svc -- wallpaper.sh --start --global
$start.BAR=hyde-shell app -u $unt-bar.scope -t $scp -- waybar.py --watch # waybar.py injects it itself as -u $unt.service :- therefore we use scope here to avoid conflicts
$start.NOTIFICATIONS=hyde-shell app -u $unt-notifications.service -t $svc -- dunst
$start.BATTERY_NOTIFY=hyde-shell app -u $unt-battery-notify.service -t $svc -- batterynotify.sh


$start.APPLET_NETWORK_MANAGER=hyde-shell app -u $unt-network-manager-applet.service -t $svc -- nm-applet --indicator
$start.APPLET_REMOVABLE_MEDIA=hyde-shell app -u $unt-removable-media-applet.service -t $svc -- udiskie --no-automount --smart-tray
$start.APPLET_BLUETOOTH=hyde-shell app -u $unt-bluetooth-applet.service -t $svc -- blueman-applet

# Unset
$unt=""
$svc=""
$scp=""


# // █▀▀ ▀█▀ █▄▀
# // █▄█ ░█░ █░█

# $default.GTK_THEME=Wallbash-Gtk
# $default.ICON_THEME=Tela-circle-dracula
# $default.COLOR_SCHEME=prefer-dark

$GTK_THEME=Wallbash-Gtk
$ICON_THEME=Tela-circle-dracula
$COLOR_SCHEME=prefer-dark

$BUTTON_LAYOUT= #? colon separated list of buttons, e.g. appmenu:minimize,maximize,close

# // █▀▀ █░█ █▀█ █▀ █▀█ █▀█
# // █▄▄ █▄█ █▀▄ ▄█ █▄█ █▀▄

$CURSOR_THEME=Bibata-Modern-Ice
$CURSOR_SIZE=24

# // █▀▀ █▀█ █▄░█ ▀█▀
# // █▀░ █▄█ █░▀█ ░█░

$FONT=Cantarell
# $FONT_STYLE=Regular
$FONT_SIZE=10
$DOCUMENT_FONT=Cantarell
$DOCUMENT_FONT_SIZE=10
$MONOSPACE_FONT=CaskaydiaCove Nerd Font Mono
$MONOSPACE_FONT_SIZE=9
$NOTIFICATION_FONT=Mononoki Nerd Font Mono
$BAR_FONT=JetBrainsMono Nerd Font
$MENU_FONT=JetBrainsMono Nerd Font #? Use the same font as the main font
$FONT_ANTIALIASING=rgba
$FONT_HINTING=

# Extra Themes
$CODE_THEME=
$SDDM_THEME=
