
[fastfetch]
    description = "A feature-rich and performance oriented neofetch like system information tool"

[[fastfetch.dependency]]
    dnf  = [ "fastfetch" ]
    pacman = [ "fastfetch" ]

[[fastfetch.files]]
    action      = "preserve"
    paths       = "fastfetch"
    source_root = "Configs/.config"
    target_root = "${XDG_CONFIG_HOME}"

[[fastfetch.files]]
    action      = "sync"
    paths       = "hyde"
    source_root = "Configs/.local/share/fastfetch/presets"
    target_root = "${HOME}/.local/share/fastfetch/presets"
