[hyprland_legacy]
description = "hyprland legacy (hyprlang) config"
conflicts = ["hyprland"]
pre_command = "echo 'Hyprland'"
post_command = "echo 'Hyprland end'"

[[hyprland_legacy.dependency]]
yay = ["hyprland"]
paru = ["hyprland"]
dnf = ["hyprland"]

# S|${HOME}/.config/hypr|animations|hyprland
# S|${HOME}/.config/hypr|workflows|hyprland
# S|${HOME}/.config/hypr|shaders|hyprland
# S|${HOME}/.config/hypr|hyprlock|hyprlock
# P|${HOME}/.config/hypr|shaders.conf workflows.conf animations.conf windowrules.conf keybindings.conf userprefs.conf monitors.conf|hyprland
# P|${HOME}/.config/hypr|nvidia.conf|hyprland nvidia-utils
# P|${HOME}/.config/hypr/themes|theme.conf wallbash.conf colors.conf|hyprland
# P|${HOME}/.config/hypr|hyprland.conf|hyprland
# P|${HOME}/.config/hypr|hyprlock.conf|hyprlock
# P|${HOME}/.config/hypr|hypridle.conf|hypridle
# P|${HOME}/.config/hypr|hyprsunset.conf|hyprsunset
[[hyprland_legacy.files]]
action = "preserve"
source_root = "Configs/.config/hypr"
target_root = "${XDG_CONFIG_HOME}/hypr"
paths = [
    "hyprland.conf",
    "shaders.conf",
    "workflows.conf",
    "animations.conf",
    "windowrules.conf",
    "keybindings.conf",
    "userprefs.conf",
    "monitors.conf",
    "themes/theme.conf",
    "themes/wallbash.conf",
    "themes/colors.conf",
]

# [hyprland_legacy_nvidia]


[[hyprland_legacy.files]]
action = "preserve"
pre_command = "./hooks/nvidia-check.sh"
source_root = "Configs/.config/hypr"
target_root = "${XDG_CONFIG_HOME}/hypr"
paths = ["nvidia.conf"]


[[hyprland_legacy.files.dependency]]
yay = ["nvidia-utils"]
dnf = ["nvidia-utils"]
pacman = ["nvidia-utils"]


[[hyprland_legacy.files]]
action = "sync"
source_root = "Configs/.local/share/hypr/"
target_root = "${XDG_DATA_HOME}/hypr/"
paths = ["*.conf"]
ignored_paths = [".vscode" , "lua" , "*.lua"]
