[global]
    description = "Choose a notification daemon. Only choose 1"
    include     = [ "../dots/dunst.toml", "../dots/swaync.toml" ]
    owner       = "The HyDE Project"
    version     = "latest"
