#!/usr/bin/env bash
# Retiring Hyprland's generated example hyprland.lua (#2132) for install.sh.
# Kept out of global_fn.sh, which every installer script sources, because only
# install.sh's restore uses it (review on #2134). Sourced after global_fn.sh:
# relies on its print_log.
#
# Not a migration: those are recorded as applied on the first install, before
# a failed deploy can leave the generated file behind. Not a deez pre_command
# on the hyprland.lua entry either: a failing hook skips that very entry.

# Replaces Hyprland's own generated example config with HyDE's hyprland.lua
# template (#2132), keeping a copy of the example.
#
# Hyprland writes that example when it starts and finds no config at all, e.g.
# after an install that failed before the dots were deployed. hyprland.lua is
# deployed with the preserve action, so HyDE then never replaces it, and the
# v26.8.1 migration only prepends the loader to it. The result loads HyDE and
# then the whole example on top as the user's override layer: Hyprland's
# default border colors and animations over every theme, and a second
# XF86AudioMute bind with different flags, so one press toggles mute twice.
#
# This runs on every restore rather than as a migration: a migration is
# recorded as applied on the first install, before a failed deploy can leave
# the window in which Hyprland generates the file.
#
# Only a byte-for-byte untouched example is replaced: Hyprland's header followed
# by the example the installed Hyprland ships, optionally behind the exact
# v26.8.1 loader. Any edit, including one inside the header or the loader,
# keeps the file in place, as does an example from another Hyprland release;
# those only get a warning (review on #2134). Comparing against the installed
# example rather than stored hashes needs no update per Hyprland release. Even
# a verified example is backed up, not deleted.
#
# A symlink is left alone: it belongs to a dotfile manager, and replacing it
# would take the machine off the managed copy.

# Hyprland's AUTOGENERATED_PREFIX_LUA (src/config/lua/DefaultConfig.hpp),
# written in front of the example; its leading newline is part of the file.
HYPR_AUTOGEN_PREFIX='
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

hl.config({ autogenerated = true }) -- remove this line to remove the warning

'
# What Scripts/migrations/v26.8.1.sh prepends, blank line included; the tests
# check the two copies stay identical.
HYDE_LUA_LOADER='-- Hyprland loads this file when it is started without a config, and it prefers
-- it over hyprland.conf. HyDE loads it too, last, as the override layer below.
-- The block keeps the two apart: hyde.lua sets `hyde` on its first line, so it
-- runs only when this file is the entry point and HyDE has not been loaded.
-- Removing it leaves a session with a cursor and nothing else.
if not hyde then
	local share = os.getenv("XDG_DATA_HOME") or (os.getenv("HOME") .. "/.local/share")
	local entry = share .. "/hypr/hyde.lua"
	local handle = io.open(entry, "r")
	if not handle then
		error("HyDE is not installed at " .. entry .. ". Run install.sh -r, or point Hyprland at your own config.")
	end
	handle:close()
	dofile(entry)
end

'

# The example the installed Hyprland embeds, which packages also install as
# <prefix>/share/hypr/hyprland.lua; the prefix is taken from the binary so
# /usr/local and Nix store builds are found too.
hypr_example_config() {
    local bin example
    bin=$(readlink -f "$(command -v Hyprland 2>/dev/null)" 2>/dev/null) || bin=""
    for example in ${bin:+"${bin%/bin/*}/share/hypr/hyprland.lua"} /usr/share/hypr/hyprland.lua; do
        [ -f "${example}" ] && [ -s "${example}" ] && [ -r "${example}" ] && {
            echo "${example}"
            return 0
        }
    done
    return 1
}

retire_autogenerated_hypr_config() {
    local target="${1:-${XDG_CONFIG_HOME:-${HOME}/.config}/hypr/hyprland.lua}"
    local backupRoot="${2:-${XDG_STATE_HOME:-${HOME}/.local/state}/hyde/backup/hyprland-autogenerated}"
    local example="${3:-}"
    local template="${4:-${cloneDir:-}/Configs/.config/hypr/hyprland.lua}"
    local backupDir staged loader matched=0

    [ -f "${target}" ] && [ ! -L "${target}" ] || return 0
    # Most files are the user's own config; only one carrying Hyprland's header
    # line is worth comparing, or warning about.
    grep -qx -- '-- AUTOGENERATED HYPRLAND CONFIG\. *--' "${target}" 2>/dev/null || return 0

    [ -n "${example}" ] || example=$(hypr_example_config) || example=""
    if [ -f "${example}" ] && [ -s "${example}" ]; then
        # Streamed into cmp rather than built in a variable: command
        # substitution would drop trailing newlines and hide an edit there.
        for loader in "" "${HYDE_LUA_LOADER}"; do
            if { printf '%s%s' "${loader}" "${HYPR_AUTOGEN_PREFIX}" && cat -- "${example}"; } |
                cmp -s -- "${target}" -; then
                matched=1
                break
            fi
        done
    fi

    if [ "${matched}" -ne 1 ]; then
        print_log -warn "Hyprland" "${target} carries Hyprland's generated-config header but could not be verified as an untouched example (edited, from another Hyprland release, or no example found at <prefix>/share/hypr/hyprland.lua); left in place. Review it: anything it sets overrides HyDE's theme and keybinds"
        return 0
    fi

    if [ "${flg_DryRun:-0}" -eq 1 ]; then
        print_log -y "[HYPRLAND] " -b "dry-run :: " "Would replace Hyprland's generated example config ${target} with HyDE's template"
        return 0
    fi

    if [ ! -f "${template}" ] || [ ! -s "${template}" ] || [ ! -r "${template}" ]; then
        print_log -warn "Hyprland" "HyDE's hyprland.lua template is missing at ${template}; left Hyprland's generated example ${target} in place"
        return 1
    fi

    # The template goes in place here rather than through the deploy, which
    # only adopts it (preserve action). Moving the example aside and leaving
    # the deploy to fill the gap left no hyprland.lua at all when the deploy
    # failed or was interrupted, and Hyprland then generates a new example,
    # without HyDE's loader (review on #2134). So: copy the example to the
    # backup first, stage the template next to the target, and rename it over
    # the target, which replaces it atomically. Any failure before the rename
    # leaves the example where it was.
    #
    # A fresh backup directory per run, so a second run never overwrites the
    # first backup even within the same second.
    if ! mkdir -p "${backupRoot}" 2>/dev/null ||
        ! backupDir=$(mktemp -d "${backupRoot}/$(date +%Y%m%d-%H%M%S).XXXX" 2>/dev/null) ||
        ! cp -p -- "${target}" "${backupDir}/hyprland.lua" 2>/dev/null; then
        [ -n "${backupDir:-}" ] && rm -rf -- "${backupDir}"
        print_log -warn "Hyprland" "Could not back up Hyprland's generated example config ${target}; left it in place, it still overrides HyDE's theme and keybinds"
        return 1
    fi

    if ! staged=$(mktemp "${target%/*}/.hyprland.lua.XXXXXX" 2>/dev/null) ||
        ! cp -- "${template}" "${staged}" 2>/dev/null ||
        ! chmod --reference="${target}" -- "${staged}" 2>/dev/null ||
        ! mv -f -- "${staged}" "${target}" 2>/dev/null; then
        [ -n "${staged:-}" ] && rm -f -- "${staged}"
        print_log -warn "Hyprland" "Could not put HyDE's template in place of ${target}; left Hyprland's generated example there (copy at ${backupDir}/hyprland.lua)"
        return 1
    fi

    print_log -g "[HYPRLAND] " -b "replaced :: " "Hyprland's generated example config, which overrode HyDE, with HyDE's template; your copy is at ${backupDir}/hyprland.lua"
    return 0
}
